### ISSUE TITLE
Use another engine instead of LaTeX to improve performance

### ISSUE THREAD

**Issue by baukker** [szhorvat/MaTeX#15]
@szhorvat Thank you for the development of MaTeX. I found that MaTeX is slow since the conversion process is complicated. If we only need to render math symbols or equations, there are other rendering engines(libraries) that is fast and can be integrated smoothly into Mathematica. I searched the Internet and found the Java library [jlatexmath](https://github.com/opencollab/jlatexmath) that can do the job. And I tried an application [mathematicallatexhelper](https://github.com/moritzfl/mathematicallatexhelper) that uses this library and found it very fast. I know the [J/Link](http://reference.wolfram.com/language/JLink/tutorial/CallingJavaFromTheWolframLanguage.html#19690) can be used to integrate this library into Mathematica, and I wonder if this is a good solution.

**Comment by szhorvat** [comment]
Thanks for the suggestion.  It would be nice to see a package using jlatexmath, but MaTeX is not that package.  MaTeX aims to interface with a true and complete TeX system.  Granted, this does come with a performance penalty, but there are multiple workarounds for that: caching (a second invocation is instantaneous) and batch processing: `MaTeX[{expr1, expr2, ...}]` uses a single call to latex, regardless of the number of expressions.

What you are proposing would require rewriting most of the package, essentially creating a whole new package.  I have neither the time nor the motivation for that (since MaTeX serves my needs well enough in its current form).  However, I encourage you to write such a package yourself if you have the necessary Java and J/Link expertise (unfortunately I don't), and I welcome you to re-use any part of MaTeX as you need (it's licensed under the MIT license).

If you do embark on this project, let me know, as I would like to see the result (and the speedups).

P.S. The reason why MaTeX is slow is not that the conversion is complicated, but that `pdflatex` takes a long time to start up.  Thus you are right that the only ways to speed it up is either using a different engine, or to persuade `pdflatex` to operate in some sort of "server mode" (i.e. start it up once and produce documents on demand).
