### ISSUE TITLE
Low Quality in ImageAssemble[{MaTeX["\\in"], MaTeX["\\in"]}]

### ISSUE THREAD

**Issue by foice** [szhorvat/MaTeX#17]
I am trying to combine some MaTeX output and I have tried `ImageAssemble[]`. The output I get is a rather low quality image. I was wondering if this is expected or there are better ways to combine the outputs of MaTeX. `GraphicsRow` does a better job but somehow put too much padding around some images. Any suggestion?

**Comment by szhorvat** [comment]
Use `Row` to combine MaTeX output. It does not rasterize, does not include padding, and respects the baseline (which MaTeX carefully preserves).

    Row[MaTeX[Text /@ Characters["Tugboat"], Magnification -> 3]]

![image](https://user-images.githubusercontent.com/1212871/30418084-16f445e6-9932-11e7-80da-166aadc5890f.png)

    MaTeX[Text@"Tugboat", Magnification -> 3]

![image](https://user-images.githubusercontent.com/1212871/30418096-1c05f44e-9932-11e7-8089-ec4207fa2006.png)


See also the example for the `ContentPadding` option in the documentation, which demonstrates that there is no padding in `Row` with `Framed`.

Why are the letter further apart then in the second example?  Two reasons:

 - LaTeX normally squeezes them together so that their boxes overlap. This way the o can enter under T in "To", and look better.

 - MaTeX inserts a padding of 1 pt to prevent font serifs that protrude from boxes from getting cut off.

You can abuse the `FrameMargins` option of `Framed` to squeeze the graphics together more tightly, like here: https://mathematica.stackexchange.com/a/131384

```mathematica
Row[Framed[#, FrameMargins -> {-3 {1, 1}, {0, 0}}, FrameStyle -> None] & /@ 
  MaTeX[Text /@ Characters["Tugboat"], Magnification -> 3]]
```

![image](https://user-images.githubusercontent.com/1212871/30418482-6c5cbabc-9933-11e7-87b7-bdf72bf0724c.png)
