### ISSUE TITLE
Building the paclet and installing it leads to corrupted documentation

### ISSUE THREAD

**Issue by msollami** [szhorvat/MaTeX#19]
I tried building the paclet by running build-paclet as detailed [here](https://mathematica.stackexchange.com/questions/131101/how-to-distribute-mathematica-packages-as-paclets), but when I search for matex I get this:

<img width="313" alt="screen shot 2017-10-10 at 10 44 21 am" src="https://user-images.githubusercontent.com/1467556/31392735-0700fb18-ada8-11e7-9149-f20732c7feca.png">

Not sure what I'm doing wrong.

**Comment by szhorvat** [comment]
Why are you trying to build it yourself instead of using the pre-built one?

https://github.com/szhorvat/MaTeX/releases

Building everything requires a complicated setup. If you just want to *use* MaTeX (not develop it), please use the pre-built paclet. The page you are linking to talks about developing your own packages, not installing others'.  Installation instructions for MaTeX are in the GitHub README.

**Comment by szhorvat** [comment]
From your question on Wolfram Community, I see that you are trying to bundle up your own package as a paclet.

The answer is that creating documentation is completely unrelated to that (although certain entries must be present in the paclet info file for documentation to work).   The MaTeX documentation is currently built using the Wolfram Workbench. What you see in the repository is source notebooks, not the final documentation.  There are tutorials on it in the Workbench reference documentation.

Additionally, the MaTeX documentation is post-processed with some custom scripts which probably only work on my own machine (due to setup issues). But you really don't need o be concerned with this for now.

**Comment by msollami** [comment]
Yes, I was just trying to recreate your steps to see how your packet is built.

**Comment by msollami** [comment]
It's a tricky process!
