### ISSUE TITLE
Produce selectable text

### ISSUE THREAD

**Issue by lucainnocenti** [szhorvat/MaTeX#4]
Hi,
Do you think it would be possible to make the generated LaTeX text selectable?

PS: Awesome work! Your package is extremely useful.

**Comment by szhorvat** [comment]
No, unfortunately that is not possible.  To make the text selectable, it would need to be _actual text_, and not just graphics (i.e. curves describing the shape of letters).  Text in Mathematica doesn't have sufficient flexibility to faithfully reproduce LaTeX output.

**Possible workarounds:**

Most of the time when MaTeX is truly needed I am making labels which have complex formulae and wouldn't be practically copyable from a PDF anyway (even if parts of the formula are technically selectable).  When I don't produce formulae, I do not use MaTeX.  Instead I use actual Mathematica text with the Latin Modern Roman font to match LaTeX's visual style.  There are a couple of examples in the [tutorial](http://szhorvat.net/pelican/latex-typesetting-in-mathematica.html).

You might also check out the [MathPSfrag package](http://packagedata.net/index.php/#package-86), which solves more or less the same problem as MaTeX with different compromises.  It _should_, in principle be able to produce selectable text, for as long as its output PDF is not imported back to Mathematica. (But again: what's the point of selecting formulae?  They aren't practically copyable anyway.)  I have not personally used this package because I was not aware of its existence when I originally wrote MaTeX.  This means I haven't actually tested whether it does produce selectable text.
